import ThemeProvider from '@/components/theme/ThemeProvider';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Roboto } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';
import { auth } from '@/../next-auth';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Stream Sphere',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="stream-sphere-theme"
          >
            <Toaster theme="dark" position="top-right" />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
